// react-app/src/App.js
import React, { Component } from 'react';
import CardList from './CardList';
import Form from './Form';

class App extends Component {
  state = {
    users: []
  };
  addCard = (user) => {
    this.setState((prevState) => ({
      users: prevState.users.concat(user)
    }));
  };

  render() {
    return (
      <div>
        <Form formSubmit={this.addCard}/>
        <CardList cards={this.state.users}/>
      </div>
    );
  }
}

export default App;

// angular-app/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  template: `
    <app-form (formSubmit)="addCard($event)" ></app-form>
    <app-card-list [cards]="users"></app-card-list>
  `
})
export class AppComponent {
  users = [];

  addCard(user) {
    this.users.push(user);
  }
}
