// react-app/src/Form.js
import React, { Component } from 'react';

class Form extends Component {
  state = {
    name: '',
    branch: ''
  };

  formHandler = (event) => {
    event.preventDefault();
    this.props.formSubmit(this.state);
  };

  render() {
    return (
      <form onSubmit={this.formHandler}>
        <input type="text" placeholder="Name" value={this.state.name}
               onChange={event => this.setState({name: event.target.value})} required/>
        <input type="text" placeholder="Branch" value={this.state.branch}
               onChange={event => this.setState({branch: event.target.value})} required/>
        <input type="submit" value="Add"/>
      </form>
    );
  }
}

export default Form;

// angular-app/src/app/form.component.ts
import { Component, Output, EventEmitter } from '@angular/core';
import { FormBuilder, FormGroup } from '@angular/forms';

@Component({
  selector: 'app-form',
  template: `
    <form [formGroup]="form" (ngSubmit)="onSubmit(form.value)">
      <input type="text" placeholder="Name" [formControl]="form.controls.name">
      <input type="text" placeholder="Branch" [formControl]="form.controls.branch">
      <input type="submit" value="Add">
    </form>
  `
})
export class FormComponent {
  @Output() formSubmit: EventEmitter<any> = new EventEmitter();
  form: FormGroup;

  constructor(private fb: FormBuilder) {
    this.form = this.fb.group({
      'name': [''],
      'branch': ['']
    });
  }

  onSubmit(value) {
    this.formSubmit.emit(value);
  }
}
